on:
  push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 25.0.2
          distribution: 'oracle'
      - name: Build
        run: ./gradlew check